### ISSUE TITLE
초기 회원 등록 시 수업 등록 일자 데이터 오류

### ISSUE THREAD

**Issue by wkdgus1164** [Dream-Maker-Inc/si_hicoach_fe#10]
1. 트레이너 회원으로 로그인 후 신규 회원 등록
2. 회원 등록 완료 후 해당 회원의 회원 상세 페이지 진입
3. 수업 등록 일자가 `1000년 02월 01일`로 나옴

TO-BE
- 수업 등록 일자를 정확한 일자 데이터로 표시

**Comment by NightOwl094** [comment]
Todo: 회원가입시에 입력한 before study는 운동 일지에 미표시
