### ISSUE TITLE
회원 아이디 검증 후 버튼 비활성화 안됨

### ISSUE THREAD

**Issue by wkdgus1164** [Dream-Maker-Inc/si_hicoach_fe#9]
1. 트레이너 회원 로그인
2. 회원 추가 화면 진입
3. 아직 매칭되지 않은 회원 검색
4. 검증 완료가 되어도 버튼 비활성화가 안됨

TO-BE
- 검증이 완료된 회원은 버튼 비활성화 후 다음으로 넘어갈 수 있어야 함

**Comment by NightOwl094** [comment]
Todo: 버튼 상태 추가
